import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import PillNav from "@/components/PillNav";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The HR Realty International",
  description: "Generated by NIKHIL TOMAR",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"> 
        <PillNav
        items={[
          {
            label: "Home",
            href: "/",
          },

           {
            label: "About-us",
            href: "/about",
          },

          {
            label: "Bulk Land",
            href: "/bulk-land",
          },

          {
            label: "Dholera SIR",
            href: "/dholera-sir",
            children: [
              {
                label: "Connectivity",
                href: "/dholera-sir/connectivity",
              },
              {
                label: "About Dholera SIR",
                href: "/dholera-sir/projects",
              },
              {
                label: "Running & Completed Projects",
                href: "/dholera-sir/running-completed-projects",
              },
              {
                label: "DMIC",
                href: "/dholera-sir/dmic",
              },
              {
                label: "DFC",
                href: "/dholera-sir/dfc",
              },
              {
                label: "GIDB",
                href: "/dholera-sir/gidb",
              },
              {
                label: "DRDA",
                href: "/dholera-sir/drda",
              },
              {
                label: "Maps",
                href: "/dholera-sir/maps",
              },
            ],
          },

          {
            label: "Projects",
            href: "/projects",
          },

          {
            label: "Sell Your Property",
            href: "/sell-your-property",
          },

          {
            label: "Contact Us",
            href: "/contact",
            children: [
              {
                label: "Careers",
                href: "/careers",
              },
            ],
          },
        ]}
        activeHref="/"
        ease="power2.out"
        baseColor="#043927"
        pillColor="transparent"
        pillTextColor="#FFFFFF"
        hoveredPillTextColor="#C9A45C"
        initialLoadAnimation
      />

        {children}
        <Footer/>
        </body>
    </html>
  );
}
